
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADDRESS AND ARROW ASSIGN AUTO BITWISE_AND BITWISE_NOT BITWISE_OR BITWISE_XOR BOOL BREAK CASE CHAR CHAR_LITERAL COLON COMMA CONST CONTINUE DECREMENT DEFAULT DEREFERENCE DIVIDE DIVIDE_ASSIGN DO DOT DOUBLE ELSE EQ EXTERN FLOAT FLOAT_NUM FOR FREE GE GT IDENTIFIER IF INCREMENT INT LBRACE LBRACKET LE LONG LPAREN LSHIFT LT MALLOC MINUS MINUS_ASSIGN MODULO NE NOT NUMBER OR PLUS PLUS_ASSIGN PRINTF QUESTION RBRACE RBRACKET REGISTER RETURN RPAREN RSHIFT SCANF SEMICOLON SHORT SIGNED SIZEOF STATIC STRING_LITERAL SWITCH TIMES TIMES_ASSIGN UNSIGNED VOID VOLATILE WHILEtest : INT IDENTIFIER ASSIGN NUMBER SEMICOLON'
    
_lr_action_items = {'INT':([0,],[2,]),'$end':([1,6,],[0,-1,]),'IDENTIFIER':([2,],[3,]),'ASSIGN':([3,],[4,]),'NUMBER':([4,],[5,]),'SEMICOLON':([5,],[6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'test':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> test","S'",1,None,None,None),
  ('test -> INT IDENTIFIER ASSIGN NUMBER SEMICOLON','test',5,'p_test','test_parser.py',14),
]
